kind: Deployment
apiVersion: apps/v1
metadata:
  name: queue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-service
  template:
    metadata:
      labels:
        app: queue-service
    spec:
      containers:
        - name: queue-service
          livenessProbe:
            exec:
              command:
                - python
                - '-m'
                - queue_service.health.check_health
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          imagePullPolicy: Always
          env:
            - name: REQUESTS_CA_BUNDLE
              value: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
          envFrom:
            - configMapRef:
                name: queue-service-config
          image: {{ template "services-chart.queueServiceImage" . }}
          args:
            - '-sk'
            - queue_service
          volumeMounts:
            - name: trusted-ca
              mountPath: /etc/pki/ca-trust/extracted/pem
              readOnly: true
      volumes:
        - name: trusted-ca
          configMap:
            name: kube-root-ca.crt
            items:
              - key: ca.crt
                path: tls-ca-bundle.pem
      restartPolicy: Always
